pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=winterbreeze
          - status-success="Travis CI - Pull Request"
          - "#approved-reviews-by>=1"
      actions:
          merge:
              method: squash
              strict: smart
