pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=master
          - status-success=Travis CI - Pull Request
          - "#approved-reviews-by>=1"
          - label≠wip
      actions:
          merge:
              method: squash
              strict: smart
              commit_message: title+body
