queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - check-success=Build and test on current ubuntu
      - check-success=Build with Clang, run linters and static analyzers
      - check-success=Build for 32bit with ancient GCC on Ubuntu 14.04
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=wip
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Build and test on current ubuntu
      - check-success=Build with Clang, run linters and static analyzers
      - check-success=Build for 32bit with ancient GCC on Ubuntu 14.04
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: Implicitly allow t-wissmann to approve own pull requests
    conditions:
      - author=t-wissmann
      - check-success=Build and test on current ubuntu
      - check-success=Build with Clang, run linters and static analyzers
      - check-success=Build for 32bit with ancient GCC on Ubuntu 14.04
      - label!=wip
      - label=self-approved
    actions:
      review:
        type: APPROVE
        message: "Approved via the `self-approved` label"
  - name: automatic merge on CI success and review
    conditions: []
    actions:
      queue:
