pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=master
          - status-success=Build and test on current ubuntu
          - status-success=Build with Clang, run linters and static analyzers
          - status-success=Build for 32bit with ancient GCC on Ubuntu 14.04
          - "#approved-reviews-by>=1"
          - label≠wip
      actions:
          merge:
              method: squash
              strict: smart
              commit_message: title+body
    - name: Implicitly allow t-wissmann to approve own pull requests
      conditions:
          - author=t-wissmann
          - status-success=Build and test on current ubuntu
          - status-success=Build with Clang, run linters and static analyzers
          - status-success=Build for 32bit with ancient GCC on Ubuntu 14.04
          - label≠wip
          - label=self-approved
      actions:
          review:
              type: APPROVE
              message: "Approved via the `self-approved` label"
