pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=winterbreeze
          - status-success=continuous-integration/travis-ci/pr
          - status-success=WIP
          - "#approved-reviews-by>=1"
      actions:
          merge:
              method: squash
              strict: smart
