FROM ubuntu:trusty-20190122

# Build deps
# TODO: Leave out git (huge and not really needed)
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    ccache \
    cmake3 \
    gcc-4.8 \
    g++-4.8 \
    git \
    libglib2.0-dev \
    libx11-dev \
    libxext-dev \
    libxinerama-dev \
    libxml2-utils \
    ninja-build \
    pkg-config \
    xterm \
    xvfb \
    && rm -rf /var/lib/apt/lists/*
