
# version is $(VERSION).$(VERSION_MINOR)

VERSION_MAJOR = 0
VERSION_MINOR = 4
# patch level
VERSION_PATCH = 0
VERSION_SUFFIX = ""
VERSION = \"$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)$(VERSION_SUFFIX)\"

