#!/bin/bash

# this is an simple config to herbstluftwm

function hc() {
    herbstclient "$@"
}

xsetroot -solid '#D47A55'


# keybindings
Mod=Mod1
hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-F2 spawn gmrun


# layouting
hc keybind $Mod-Shift-h split '(cur)' horizontal 0.5
hc keybind $Mod-Shift-v split '(cur)' vertical 0.5

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right


