#!/bin/bash

# this is an simple config to herbstluftwm

function hc() {
    herbstclient "$@"
}

xsetroot -solid '#D47A55'


# keybindings
Mod=Mod1
hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-F2 spawn gmrun

# tags
for i in {1..9} ; do
    hc add "$i"
    hc keybind "$Mod-$i" use "$i"
    hc keybind "$Mod-Shift-$i" move "$i"
done
hc keybind "$Mod-0" use default

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split '(cur)' vertical 0.5
hc keybind $Mod-o split '(cur)' horizontal 0.5

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_border_active_color '#49351D'
hc set frame_border_normal_color '#73532D'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 2
hc set window_border_width 3
hc set window_border_normal_color '#AE8451'
hc set window_border_active_color '#F6FF00'


