#!/bin/bash

# this is an simple config to herbstluftwm

function hc() {
    herbstclient "$@"
}

xsetroot -solid '#D47A55'

Mod=Mod1
hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-F2 spawn gmrun


# layouting
hc keybind $Mod-h split '(cur)' horizontal 0.5
hc keybind $Mod-v split '(cur)' vertical 0.5



