#pragma once

#include <memory>
#include <string>

#include "framedata.h"

/*! A 'pure' parser a layout description generated by the 'dump' command.
 *
 * Pure means that it does not affect the actual tiling tree. The purpose is to
 * first parse and validate the input string. The application of this parsing
 * result to the actual frame tree is done by the respective command in the
 * FrameTree class.
 *
 * Hence, the result of this parsing process is a 'raw tree', meaning a tree of
 * RawFrameNode objects, i.e. actually of RawFrameLeaf, RawFrameSplit. All the
 * members are already validated, so e.g. invalid window ids are already
 * filtered.
 *
 */

class RawFrameNode {
protected:
    RawFrameNode() {};
};

class RawFrameLeaf : public RawFrameNode,
                     public FrameDataLeaf {
public:
};

class RawFrameSplit : public RawFrameNode,
                      public FrameDataSplit<RawFrameNode> {
public:
};

/*! the FrameParser is actually only a interface to access the parsing result
 * and possible error messages, because the parser methods are private member
 * functions. The parsing starts already in the constructor.
 */
class FrameParser {
public:
    FrameParser(std::string buf);
    //! the parsing result
    std::shared_ptr<RawFrameNode> root_;
    //! a possible error message and the position where it occured
    std::pair<int,std::string> error_;

    //! a list of tokens and their positions
    using Tokens = std::vector<std::pair<size_t,std::string>>;
private:
    void parse(std::string buf);
    //! Split a string into tokens. The tokens are defined in the sense that it
    //is always allowed to insert spaces between tokens. Hence in (a (b c)) the
    //two closing brackets are separate tokens because (a (b c) ) is
    //equivalent; however the Leaf-args string "vertical:0" is a single token
    //because "vertical: 0" is not of valid syntax.
    Tokens tokenize(std::string buf);

    //! the next token to process by buildTree()
    Tokens::const_iterator nextToken;
    Tokens::const_iterator endToken;
    //! build a RawFrameNode-Tree from the token list
    std::shared_ptr<RawFrameNode> buildTree();
    void expectTokens(std::vector<std::string> token);

    //! tells whether the given char is contained in the string
    static bool contained_in(char c, std::string s);
};
